name: ml-latest
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - numpy<1.16.5
    - uproot<4
    - tensorflow
    - xrootd
    - scikit-learn
    - matplotlib
    - tqdm
    - pip
    - pip:
      - --find-links https://download.pytorch.org/whl/torch_stable.html 
      - --find-links https://pytorch-geometric.com/whl/torch-1.5.0+cpu.html
      - torch==1.5.0+cpu
      - torchvision==0.6.0+cpu
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
      - torch-geometric
      - mplhep
      - jupyter-book
